spring.application.name=report-service

spring.config.import=optional:file:../secrets.properties,optional:file:secrets.properties,optional:file:../../secrets.properties

spring.datasource.url=${DB_URL:jdbc:sqlserver://smzen-capstone.database.windows.net:1433;database=smzen-capstone-db;user=cs_admin@smzen-capstone;password=Capstone@;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;}
spring.datasource.username=${DB_USERNAME:cs_admin}
spring.datasource.password=${DB_PASSWORD:Capstone@}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none

# Custom path for the interactive Swagger HTML UI
springdoc.swagger-ui.path=/swagger-ui.html

# Custom path for the raw JSON OpenAPI specification
springdoc.api-docs.path=/v3/api-docs

