spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://team6-report-service.vault.azure.net/

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true

# Custom path for the interactive Swagger HTML UI
springdoc.swagger-ui.path=/swagger-ui.html

# Custom path for the raw JSON OpenAPI specification
springdoc.api-docs.path=/v3/api-docs
