spring.application.name=document-service
server.port=8080

spring.datasource.url=jdbc:sqlserver://smzen-capstone.database.windows.net:1433;database=smzen-capstone-db;user=cs_admin@smzen-capstone;password=Capstone@;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=cs_admin
spring.datasource.password=Capstone@
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
# spring.datasource.url=jdbc:h2:mem:documentdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# spring.sql.init.mode=always
# spring.jpa.defer-datasource-initialization=true
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Custom path for the interactive Swagger HTML UI
springdoc.swagger-ui.path=/swagger-ui.html

# Custom path for the raw JSON OpenAPI specification
springdoc.api-docs.path=/v3/api-docs