CREATE TABLE IF NOT EXISTS document_types (
    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code VARCHAR(50) NOT NULL UNIQUE,
    category_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_mandatory BOOLEAN NOT NULL DEFAULT TRUE,
    max_size_mb INT NOT NULL DEFAULT 10,
    allowed_extensions VARCHAR(100) DEFAULT 'pdf,jpg,jpeg,png',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(100) NOT NULL,
    application_id VARCHAR(100),
    document_type VARCHAR(50) NOT NULL,
    document_type_code VARCHAR(50),
    document_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255),
    blob_path VARCHAR(500),
    blob_url VARCHAR(1000),
    content_type VARCHAR(100),
    file_size_bytes BIGINT,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS document_versions (
    version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version_number INT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    blob_path VARCHAR(500),
    blob_url VARCHAR(1000),
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    file_data BLOB,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_document_versions_document
        FOREIGN KEY (document_id)
        REFERENCES documents(document_id)
        ON DELETE CASCADE
);