-- =============================================================================
-- MSSQL SCHEMA DDL FOR LOAN SERVICE (CAPITAL LETTERS)
-- Database: smzen-capstone-db
-- =============================================================================

-- 1. LOAN_SCHEMES TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOAN_SCHEMES' AND type = 'U')
BEGIN
    CREATE TABLE LOAN_SCHEMES (
        SCHEME_ID VARCHAR(36) NOT NULL,
        LOAN_TYPE VARCHAR(30) NOT NULL,
        SCHEME_NAME VARCHAR(100) NOT NULL,
        MIN_AMOUNT DECIMAL(18, 2) NOT NULL,
        MAX_AMOUNT DECIMAL(18, 2) NOT NULL,
        MIN_TENURE_MONTHS INT NOT NULL,
        MAX_TENURE_MONTHS INT NOT NULL,
        BASE_INTEREST_RATE DECIMAL(5, 2) NOT NULL,
        IS_ACTIVE BIT NOT NULL CONSTRAINT DF_LOAN_SCHEMES_IS_ACTIVE DEFAULT 1,
        CONSTRAINT PK_LOAN_SCHEMES PRIMARY KEY (SCHEME_ID)
    );
    PRINT 'Created table LOAN_SCHEMES';
END;

-- 2. LOAN_APPLICATIONS TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOAN_APPLICATIONS' AND type = 'U')
BEGIN
    CREATE TABLE LOAN_APPLICATIONS (
        APPLICATION_ID VARCHAR(36) NOT NULL,
        CUSTOMER_ID VARCHAR(36) NOT NULL,
        CUSTOMER_NAME VARCHAR(100) NOT NULL,
        CUSTOMER_EMAIL VARCHAR(100) NOT NULL,
        CUSTOMER_PHONE VARCHAR(20) NOT NULL,
        MONTHLY_INCOME DECIMAL(18, 2) NOT NULL,
        EXISTING_LIABILITIES DECIMAL(18, 2) CONSTRAINT DF_LOAN_APPS_EXISTING_LIAB DEFAULT 0.00,
        EMPLOYMENT_TYPE VARCHAR(50) NOT NULL,
        SCHEME_ID VARCHAR(36) NOT NULL,
        LOAN_TYPE VARCHAR(30) NOT NULL,
        LOAN_AMOUNT DECIMAL(18, 2) NOT NULL,
        DOCUMENT_PROVIDED BIT NOT NULL CONSTRAINT DF_LOAN_APPS_DOC_PROVIDED DEFAULT 0,
        TENURE_MONTHS INT NOT NULL,
        INTEREST_RATE DECIMAL(5, 2) NOT NULL,
        CALCULATED_EMI DECIMAL(18, 2) NOT NULL,
        STATUS VARCHAR(30) NOT NULL,
        RISK_SCORE INT NULL,
        DTI_RATIO DECIMAL(5, 2) NULL,
        ORCHESTRATION_INSTANCE_ID VARCHAR(100) NULL,
        ASSIGNED_MANAGER VARCHAR(100) NULL,
        DECISION_REMARKS VARCHAR(1000) NULL,
        CREATED_AT DATETIME2 NOT NULL CONSTRAINT DF_LOAN_APPS_CREATED_AT DEFAULT SYSUTCDATETIME(),
        UPDATED_AT DATETIME2 NOT NULL CONSTRAINT DF_LOAN_APPS_UPDATED_AT DEFAULT SYSUTCDATETIME(),
        CREATED_BY VARCHAR(100) NOT NULL CONSTRAINT DF_LOAN_APPS_CREATED_BY DEFAULT 'SYSTEM',
        CREATED_DATE DATETIME2 NOT NULL CONSTRAINT DF_LOAN_APPS_CREATED_DATE DEFAULT SYSUTCDATETIME(),
        LAST_MODIFIED_BY VARCHAR(100) NULL,
        LAST_MODIFIED_DATE DATETIME2 NULL,
        CONSTRAINT PK_LOAN_APPLICATIONS PRIMARY KEY (APPLICATION_ID),
        CONSTRAINT FK_LOAN_APPS_SCHEME FOREIGN KEY (SCHEME_ID) REFERENCES LOAN_SCHEMES (SCHEME_ID)
    );
    PRINT 'Created table LOAN_APPLICATIONS';
END
ELSE
BEGIN
    -- Ensure columns exist if table was already created
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('LOAN_APPLICATIONS') AND name = 'SCHEME_ID')
    BEGIN
        ALTER TABLE LOAN_APPLICATIONS ADD SCHEME_ID VARCHAR(36) NULL;
        PRINT 'Added column SCHEME_ID to LOAN_APPLICATIONS';
    END;
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('LOAN_APPLICATIONS') AND name = 'DOCUMENT_PROVIDED')
    BEGIN
        ALTER TABLE LOAN_APPLICATIONS ADD DOCUMENT_PROVIDED BIT NOT NULL CONSTRAINT DF_LOAN_APPS_DOC_PROVIDED_ALT DEFAULT 0;
        PRINT 'Added column DOCUMENT_PROVIDED to LOAN_APPLICATIONS';
    END;
END;

-- 3. LOAN_DOCUMENTS TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOAN_DOCUMENTS' AND type = 'U')
BEGIN
    CREATE TABLE LOAN_DOCUMENTS (
        DOCUMENT_ID VARCHAR(36) NOT NULL,
        APPLICATION_ID VARCHAR(36) NULL,
        CUSTOMER_ID VARCHAR(36) NOT NULL,
        DOC_TYPE VARCHAR(50) NOT NULL,
        FILE_NAME VARCHAR(255) NOT NULL,
        CONTENT_TYPE VARCHAR(100) NOT NULL,
        BLOB_STORAGE_PATH VARCHAR(500) NOT NULL,
        FILE_SIZE_BYTES BIGINT NOT NULL,
        UPLOADED_AT DATETIME2 NOT NULL CONSTRAINT DF_LOAN_DOCS_UPLOADED_AT DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_LOAN_DOCUMENTS PRIMARY KEY (DOCUMENT_ID),
        CONSTRAINT FK_LOAN_DOCS_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATIONS (APPLICATION_ID)
    );
    PRINT 'Created table LOAN_DOCUMENTS';
END;

-- 4. LOAN_AUDIT_LOGS TABLE
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOAN_AUDIT_LOGS' AND type = 'U')
BEGIN
    CREATE TABLE LOAN_AUDIT_LOGS (
        LOG_ID BIGINT IDENTITY(1,1) NOT NULL,
        APPLICATION_ID VARCHAR(36) NOT NULL,
        PREVIOUS_STATUS VARCHAR(30) NULL,
        NEW_STATUS VARCHAR(30) NOT NULL,
        CHANGED_BY VARCHAR(100) NOT NULL,
        COMMENTS VARCHAR(1000) NULL,
        TIMESTAMP DATETIME2 NOT NULL CONSTRAINT DF_LOAN_AUDIT_TIMESTAMP DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_LOAN_AUDIT_LOGS PRIMARY KEY (LOG_ID)
    );
    PRINT 'Created table LOAN_AUDIT_LOGS';
END;

-- 5. HIBERNATE ENVERS REVISION TABLE (REVINFO)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'REVINFO' AND type = 'U')
BEGIN
    CREATE TABLE REVINFO (
        REV INT IDENTITY(1,1) NOT NULL,
        REVTSTMP BIGINT NULL,
        CONSTRAINT PK_REVINFO PRIMARY KEY (REV)
    );
    PRINT 'Created table REVINFO';
END;

-- 6. HIBERNATE ENVERS AUDIT TABLE: LOAN_APPLICATIONS_AUD
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOAN_APPLICATIONS_AUD' AND type = 'U')
BEGIN
    CREATE TABLE LOAN_APPLICATIONS_AUD (
        APPLICATION_ID VARCHAR(36) NOT NULL,
        REV INT NOT NULL,
        REVTYPE TINYINT NOT NULL,
        CUSTOMER_ID VARCHAR(36) NULL,
        CUSTOMER_NAME VARCHAR(100) NULL,
        CUSTOMER_EMAIL VARCHAR(100) NULL,
        CUSTOMER_PHONE VARCHAR(20) NULL,
        MONTHLY_INCOME DECIMAL(18, 2) NULL,
        EXISTING_LIABILITIES DECIMAL(18, 2) NULL,
        EMPLOYMENT_TYPE VARCHAR(50) NULL,
        SCHEME_ID VARCHAR(36) NULL,
        LOAN_TYPE VARCHAR(30) NULL,
        LOAN_AMOUNT DECIMAL(18, 2) NULL,
        DOCUMENT_PROVIDED BIT NULL,
        TENURE_MONTHS INT NULL,
        INTEREST_RATE DECIMAL(5, 2) NULL,
        CALCULATED_EMI DECIMAL(18, 2) NULL,
        STATUS VARCHAR(30) NULL,
        RISK_SCORE INT NULL,
        DTI_RATIO DECIMAL(5, 2) NULL,
        ORCHESTRATION_INSTANCE_ID VARCHAR(100) NULL,
        ASSIGNED_MANAGER VARCHAR(100) NULL,
        DECISION_REMARKS VARCHAR(1000) NULL,
        CREATED_AT DATETIME2 NULL,
        UPDATED_AT DATETIME2 NULL,
        CREATED_BY VARCHAR(100) NULL,
        CREATED_DATE DATETIME2 NULL,
        LAST_MODIFIED_BY VARCHAR(100) NULL,
        LAST_MODIFIED_DATE DATETIME2 NULL,
        CONSTRAINT PK_LOAN_APPLICATIONS_AUD PRIMARY KEY (APPLICATION_ID, REV),
        CONSTRAINT FK_LOAN_APPS_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO (REV)
    );
    PRINT 'Created table LOAN_APPLICATIONS_AUD';
END;

-- 7. HIBERNATE ENVERS AUDIT TABLE: LOAN_DOCUMENTS_AUD
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'LOAN_DOCUMENTS_AUD' AND type = 'U')
BEGIN
    CREATE TABLE LOAN_DOCUMENTS_AUD (
        DOCUMENT_ID VARCHAR(36) NOT NULL,
        REV INT NOT NULL,
        REVTYPE TINYINT NOT NULL,
        APPLICATION_ID VARCHAR(36) NULL,
        CUSTOMER_ID VARCHAR(36) NULL,
        DOC_TYPE VARCHAR(50) NULL,
        FILE_NAME VARCHAR(255) NULL,
        CONTENT_TYPE VARCHAR(100) NULL,
        BLOB_STORAGE_PATH VARCHAR(500) NULL,
        FILE_SIZE_BYTES BIGINT NULL,
        UPLOADED_AT DATETIME2 NULL,
        CONSTRAINT PK_LOAN_DOCUMENTS_AUD PRIMARY KEY (DOCUMENT_ID, REV),
        CONSTRAINT FK_LOAN_DOCS_AUD_REV FOREIGN KEY (REV) REFERENCES REVINFO (REV)
    );
    PRINT 'Created table LOAN_DOCUMENTS_AUD';
END;

-- 8. SEED INITIAL LOAN SCHEMES IF NOT PRESENT
IF NOT EXISTS (SELECT 1 FROM LOAN_SCHEMES WHERE SCHEME_ID = 'SCHEME-PL-01')
BEGIN
    INSERT INTO LOAN_SCHEMES (SCHEME_ID, LOAN_TYPE, SCHEME_NAME, MIN_AMOUNT, MAX_AMOUNT, MIN_TENURE_MONTHS, MAX_TENURE_MONTHS, BASE_INTEREST_RATE, IS_ACTIVE)
    VALUES ('SCHEME-PL-01', 'PERSONAL_LOAN', 'Prime Flexi Personal Loan', 10000.00, 1000000.00, 6, 60, 11.50, 1);
END;

IF NOT EXISTS (SELECT 1 FROM LOAN_SCHEMES WHERE SCHEME_ID = 'SCHEME-HL-01')
BEGIN
    INSERT INTO LOAN_SCHEMES (SCHEME_ID, LOAN_TYPE, SCHEME_NAME, MIN_AMOUNT, MAX_AMOUNT, MIN_TENURE_MONTHS, MAX_TENURE_MONTHS, BASE_INTEREST_RATE, IS_ACTIVE)
    VALUES ('SCHEME-HL-01', 'HOME_LOAN', 'Dream Home Mortgage Scheme', 500000.00, 50000000.00, 36, 360, 8.40, 1);
END;

IF NOT EXISTS (SELECT 1 FROM LOAN_SCHEMES WHERE SCHEME_ID = 'SCHEME-VL-01')
BEGIN
    INSERT INTO LOAN_SCHEMES (SCHEME_ID, LOAN_TYPE, SCHEME_NAME, MIN_AMOUNT, MAX_AMOUNT, MIN_TENURE_MONTHS, MAX_TENURE_MONTHS, BASE_INTEREST_RATE, IS_ACTIVE)
    VALUES ('SCHEME-VL-01', 'VEHICLE_LOAN', 'DriveSmart Auto Loan', 100000.00, 5000000.00, 12, 60, 9.20, 1);
END;

IF NOT EXISTS (SELECT 1 FROM LOAN_SCHEMES WHERE SCHEME_ID = 'SCHEME-EL-01')
BEGIN
    INSERT INTO LOAN_SCHEMES (SCHEME_ID, LOAN_TYPE, SCHEME_NAME, MIN_AMOUNT, MAX_AMOUNT, MIN_TENURE_MONTHS, MAX_TENURE_MONTHS, BASE_INTEREST_RATE, IS_ACTIVE)
    VALUES ('SCHEME-EL-01', 'EDUCATION_LOAN', 'Global Scholar Education Loan', 50000.00, 7500000.00, 12, 180, 8.75, 1);
END;

PRINT 'MSSQL Loan Service Schema initialization completed successfully.';
